set echo on
set define off
whenever sqlerror exit sql.sqlcode rollback

-- =============================================================================
-- Migration Tracker - Final visible app pages
-- Anwendung: 114  Workspace: MIGRATION  Schema: MIGRATION
--
-- Visible final pages:
--   Page 1  APEX Migration Übersicht
--   Page 10 Live Vergleich
--
-- Page 9 remains as technical/detail page behind Live Vergleich.
-- Pages 2-8 are removed.
-- =============================================================================

declare
    l_count number;
begin
    select count(*)
    into   l_count
    from   all_tables
    where  owner = sys_context('USERENV', 'CURRENT_SCHEMA')
    and    table_name = 'MT_APEX_MIGRATION_OVERVIEW';

    if l_count = 0 then
        execute immediate q'[
            create table mt_apex_migration_overview (
                overview_id         number generated by default as identity,
                row_sort            number not null,
                umgebung            varchar2(100),
                datenbank           varchar2(200),
                quelle_host_db_pdb   varchar2(1000),
                ziel_host_db_pdb     varchar2(1000),
                service_name_ziel    varchar2(200),
                apex_version         varchar2(200),
                status               varchar2(100),
                url                  varchar2(1000),
                constraint pk_mt_apex_migration_overview primary key (overview_id),
                constraint uq_mt_apex_mig_ovw_sort unique (row_sort)
            )
        ]';
    end if;
end;
/

create or replace trigger bi_mt_apex_mig_ovw
before insert on mt_apex_migration_overview
for each row
when (new.row_sort is null)
declare
    l_next_sort number;
begin
    select nvl(max(row_sort), 0) + 10
    into   l_next_sort
    from   mt_apex_migration_overview;

    :new.row_sort := l_next_sort;
end;
/

delete from mt_apex_migration_overview;

insert into mt_apex_migration_overview (
    row_sort, umgebung, datenbank, quelle_host_db_pdb, ziel_host_db_pdb,
    service_name_ziel, apex_version, status, url
) values (
    10, q'[AEN]', q'[SEMINR]', q'[rzhs184_SEMINR_SEMINARPROD]', q'[rzhs440_SEMINR_SEMINARPROD]',
    q'[SEMINAR.PROD]', q'[21.1.5 + UPDATE?]', q'[MIGRIERT]', q'[https://rzhs440.ofd-h.de:8140/ords/f?p=4550:1]'
);
insert into mt_apex_migration_overview values (
    default, 20, null, null, q'[rzhs184_SEMINR_SEMINARINT]', q'[rzhs440_SEMINR_SEMINARINT]',
    q'[SEMINAR.INT]', q'[21.1.5 + UPDATE?]', q'[MIGRIERT]', q'[https://rzhs440.ofd-h.de:8141/ords/f?p=4550:1]'
);
insert into mt_apex_migration_overview values (
    default, 30, null, null, q'[rzhs184_SEMINR_SEMINARENTW]', q'[rzhs440_SEMINR_SEMINARENTW]',
    q'[SEMINAR.ENTW]', q'[24.1 + VALIDIERT?]', q'[MIGRIERT]', q'[https://rzhs440.ofd-h.de:8142/ords/r/apex/workspace-sign-in]'
);

insert into mt_apex_migration_overview values (
    default, 40, q'[AEN]', q'[DBAE21 (OPK)]', q'[rzhs184_DBAE21_OPK.PROD]', q'[rzhs440_DBAE21_OPK.PROD]',
    q'[OPK.PROD]', q'[21.1.5 + UPDATE?]', q'[MIGRIERT]', q'[https://rzhs440.ofd-h.de:8110/ords/f?p=4550:1]'
);
insert into mt_apex_migration_overview values (
    default, 50, null, null, q'[rzhs184_DBAE21_OPK.INT]', q'[rzhs440_DBAE21_OPK.INT]',
    q'[OPK.INT]', q'[21.1.5 + UPDATE?]', q'[MIGRIERT]', q'[https://rzhs440.ofd-h.de:8111/ords/f?p=4550:1]'
);
insert into mt_apex_migration_overview values (
    default, 60, null, null, q'[rzhs184_DBAE21_OPK.ENTW]', q'[rzhs440_DBAE21_OPK.ENTW]',
    q'[OPK.ENTW]', q'[24.1 + VALIDIERT?]', q'[MIGRIERT]', q'[https://rzhs440.ofd-h.de:8112/ords/r/apex/workspace-sign-in]'
);

insert into mt_apex_migration_overview values (
    default, 70, q'[AEN]', q'[SUPPORTFR]', q'[rzhs184_SUPPORTFR_SUPPORTFREEPROD]', q'[rzhs441_SUPPORTFR_SUPPORTFREEPROD]',
    q'[SUPPORT_FREE.PROD]', q'[21.1.5 + UPDATE?]', q'[MIGRIERT]', q'[https://rzhs441.ofd-h.de:8160/ords/f?p=4550:1]'
);
insert into mt_apex_migration_overview values (
    default, 80, null, null, q'[rzhs184_SUPPORTFR_SUPPORTFREEINT]', q'[rzhs441_SUPPORTFR_SUPPORTFREEINT]',
    q'[SUPPORT_FREE.INT]', q'[21.1.5 + UPDATE?]', q'[MIGRIERT]', q'[https://rzhs441.ofd-h.de:8161/ords/f?p=4550:1]'
);
insert into mt_apex_migration_overview values (
    default, 90, null, null, q'[rzhs184_SUPPORTFR_SUPPORTFREEENTW]', q'[rzhs441_SUPPORTFR_SUPPORTFREEENTW]',
    q'[SUPPORT_FREE.ENTW]', q'[24.1 + VALIDIERT?]', q'[MIGRIERT]', q'[https://rzhs441.ofd-h.de:8162/ords/r/apex/workspace-sign-in]'
);

insert into mt_apex_migration_overview values (
    default, 100, q'[AEN]', q'[PNGO]', q'[rzhs184_PNGO_PINGOPROD]', q'[rzhs442_PNGO_PINGOPROD]',
    q'[PINGO.PROD]', q'[21.1.5 + UPDATE?]', q'[MIGRIERT]', q'[https://rzhs442.ofd-h.de:8130/ords/f?p=4550:1]'
);
insert into mt_apex_migration_overview values (
    default, 110, null, null, q'[rzhs184_PNGO_PINGOINT]', q'[rzhs422_PNGO_PINGOINT]',
    q'[PINGO.INT]', q'[21.1.5 + UPDATE?]', q'[MIGRIERT]', q'[https://rzhs442.ofd-h.de:8131/ords/f?p=4550:1]'
);
insert into mt_apex_migration_overview values (
    default, 120, null, null, q'[rzhs184_PNGO_PINGOENTW]', q'[rzhs442_PNGO_PINGOENTW]',
    q'[PINGO.ENTW]', q'[24.1 + VALIDIERT?]', q'[MIGRIERT]', q'[https://rzhs442.ofd-h.de:8132/ords/f?p=4550:1]'
);

insert into mt_apex_migration_overview values (
    default, 130, q'[AEN]', q'[ITFALL (IT-Fallauswahl)]',
    q'[rzhs159_ITPRODS (Data Guard Primary derzeit) + rzhs158_ITPROD (Data Guard Standby derzeit)]',
    q'[rzhs441_ITFALL_ITFALLPROD]', q'[ITFALL.PROD]', q'[5.0.4.00.12 + UPDATE?]',
    q'[MIGRIERT]', q'[https://rzhs441.ofd-h.de:8180/ords/]'
);
insert into mt_apex_migration_overview values (
    default, 140, null, null,
    q'[rzhs159_ITPRODS (Data Guard Primary derzeit) + rzhs158_ITPROD (Data Guard Standby derzeit)]',
    q'[rzhs441_ITFALL_ITFALLINT]', q'[ITFALL.INT]', q'[24.1 + VALIDIERT?]',
    q'[MIGRIERT]', q'[https://rzhs441.ofd-h.de:8081/ords/r/apex/workspace-sign-in]'
);
insert into mt_apex_migration_overview values (
    default, 150, null, null,
    q'[rzhs159_ITPRODS (Data Guard Primary derzeit) + rzhs158_ITPROD (Data Guard Standby derzeit)]',
    q'[rzhs441_ITFALL_ITFALLENTW]', q'[ITFALL.ENTW]', q'[21.1.5 + UPDATE?]',
    q'[MIGRIERT]', q'[https://rzhs441.ofd-h.de:8182/ords/]'
);

insert into mt_apex_migration_overview values (
    default, 160, unistr('\2014'), q'[GG]', q'[rzhs406_PARADO_PARADOX (Prod)]', q'[rzhs440_GG_GGPROD]',
    q'[GG.PRD]', q'[20.2.0.00.20 + UPDATE?]', q'[MIGRIERT]', q'[https://rzhs440.ofd-h.de:9090/ords/]'
);
insert into mt_apex_migration_overview values (
    default, 170, null, null, q'[rzhs406_PARADO_PARADOX (Prod)]', q'[rzhs440_GG_GGINT]',
    q'[GG.INT]', q'[24.1 + VALIDIERT?]', q'[MIGRIERT]', q'[https://rzhs440.ofd-h.de:9091/ords/r/apex/workspace-sign-in/]'
);
insert into mt_apex_migration_overview values (
    default, 180, null, null, q'[rzhs_406_PARADO_PARADOX]', q'[rzhs440_GG_GGENTW]',
    q'[GG.ENTW]', q'[24.1 + VALIDIERT?]', q'[MIGRIERT]', q'[https://rzhs440.ofd-h.de:9092/ords]'
);

commit;

declare
    l_workspace_id number;
    l_app_id       number;
    l_nav_list_id  number;
begin
    select workspace_id
    into   l_workspace_id
    from   apex_workspaces
    where  workspace = 'MIGRATION';

    apex_util.set_security_group_id(l_workspace_id);

    select application_id
    into   l_app_id
    from (
        select application_id
        from   apex_applications
        where  workspace = 'MIGRATION'
        and    application_name = 'Migration_Tracker'
        order  by application_id
    )
    where rownum = 1;

    select list_id
    into   l_nav_list_id
    from   apex_application_lists
    where  application_id = l_app_id
    and    list_name = 'Navigation Menu';

    wwv_flow_imp.import_begin(
        p_version_yyyy_mm_dd     => '2024.05.31',
        p_release                => '24.1.0',
        p_default_workspace_id   => l_workspace_id,
        p_default_application_id => l_app_id,
        p_default_id_offset      => 0,
        p_default_owner          => 'MIGRATION');

    -- Recreate the app landing page as the final overview.
    wwv_flow_imp_page.remove_page(p_flow_id => l_app_id, p_page_id => 1);
    wwv_flow_imp_page.create_page(
        p_id                    => 1,
        p_name                  => 'APEX Migration ' || unistr('\00DC') || 'bersicht',
        p_alias                 => 'APEX-MIGRATION-UEBERSICHT',
        p_step_title            => 'APEX Migration ' || unistr('\00DC') || 'bersicht',
        p_autocomplete_on_off   => 'OFF',
        p_page_template_options => '#DEFAULT#',
        p_protection_level      => 'C',
        p_page_component_map    => '11');

    wwv_flow_imp_page.create_page_plug(
        p_id                    => wwv_flow_imp.id(91500000000000001),
        p_plug_name             => 'Final Navigation Cleanup',
        p_plug_display_sequence => 1,
        p_plug_display_point    => 'BODY',
        p_plug_source_type      => 'NATIVE_STATIC',
        p_plug_source           => q'~<style>
.t-Body-nav,.t-TreeNav{visibility:hidden}
.mt-overview-wrap{overflow:auto}
.mt-overview-table{border-collapse:separate;border-spacing:0;width:100%;font-size:.84rem;border:1px solid #d0d7de;border-radius:6px;overflow:hidden}
.mt-overview-table th{background:#f6f8fa;color:#172033;font-weight:700;border-bottom:1px solid #c9d1d9;padding:7px 9px;text-align:left;white-space:nowrap}
.mt-overview-table td{padding:7px 9px;border-bottom:1px solid #d8dee4;vertical-align:top;white-space:nowrap}
.mt-overview-table tr:nth-child(4n+1) td{background:#fff1f1}
.mt-overview-table tr:nth-child(4n+2) td{background:#fff7d6}
.mt-overview-table tr:nth-child(4n+3) td{background:#eefcf4}
.mt-overview-table tr:nth-child(4n+4) td{background:#eef6ff}
.mt-badge{display:inline-block;padding:2px 8px;border-radius:999px;font-size:.72rem;font-weight:700}
.mt-badge-ok{background:#d1fae5;color:#065f46}
.mt-badge-warn{background:#fee2e2;color:#991b1b}
.mt-link{color:#005ea8;text-decoration:none}
.mt-link:hover{text-decoration:underline}
</style>
<script>
(function(){
  function hideOldNavEntries(){
    var hiddenTexts = {
      "Home": true,
      "Fachverfahren": true,
      "Caesar Orders": true,
      "Checkliste": true,
      "Service Name Audit": true,
      "Server Inventory": true
    };
    document.querySelectorAll(".t-TreeNav a, .t-Body-nav a, nav a").forEach(function(anchor){
      var text = (anchor.textContent || "").replace(/\s+/g, " ").trim();
      var href = anchor.getAttribute("href") || "";
      if (hiddenTexts[text] || /[:.]([2-8])[:.]/.test(href)) {
        var row = anchor.closest("li");
        if (row) {
          row.style.display = "none";
        } else {
          anchor.style.display = "none";
        }
      }
    });
    document.querySelectorAll(".t-Body-nav,.t-TreeNav,nav").forEach(function(nav){
      nav.style.visibility = "visible";
    });
  }
  hideOldNavEntries();
  document.addEventListener("apexreadyend", hideOldNavEntries);
  window.setTimeout(hideOldNavEntries, 300);
})();
</script>~',
        p_attributes            => wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
            'expand_shortcuts', 'N',
            'output_as',        'HTML',
            'show_line_breaks', 'N')).to_clob);

    wwv_flow_imp_page.create_page_plug(
        p_id                      => wwv_flow_imp.id(91500000000000010),
        p_plug_name               => 'APEX Migration ' || unistr('\00DC') || 'bersicht',
        p_title                   => 'APEX Migration ' || unistr('\00DC') || 'bersicht',
        p_plug_template           => wwv_flow_imp.id(10818657374759767),
        p_region_css_classes      => 'mt-overview',
        p_region_template_options => '#DEFAULT#:t-Region--scrollBody',
        p_plug_display_sequence   => 999,
        p_plug_display_point      => 'BODY',
        p_plug_display_condition_type => 'NEVER',
        p_query_type              => 'SQL',
        p_plug_source             => wwv_flow_string.join(wwv_flow_t_varchar2(
            'select overview_id,',
            '       row_sort,',
            '       umgebung,',
            '       datenbank,',
            '       quelle_host_db_pdb,',
            '       ziel_host_db_pdb,',
            '       service_name_ziel,',
            '       apex_version,',
            '       status,',
            '       url',
            'from   mt_apex_migration_overview')),
        p_include_rowid_column    => false,
        p_is_editable             => true,
        p_edit_operations         => 'i:u:d',
        p_lost_update_check_type  => 'VALUES',
        p_plug_source_type        => 'NATIVE_IG');

    wwv_flow_imp_page.create_page_plug(
        p_id                      => wwv_flow_imp.id(91500000000000100),
        p_plug_name               => 'APEX Migration ' || unistr('\00DC') || 'bersicht Tabelle',
        p_title                   => 'APEX Migration ' || unistr('\00DC') || 'bersicht',
        p_plug_template           => wwv_flow_imp.id(10818657374759767),
        p_region_template_options => '#DEFAULT#:t-Region--scrollBody',
        p_plug_display_sequence   => 10,
        p_plug_display_point      => 'BODY',
        p_plug_source_type        => 'NATIVE_PLSQL',
        p_plug_source             => q'~declare
    l_rows number := 0;

    function esc(p_text in varchar2) return varchar2 is
    begin
        return apex_escape.html(p_text);
    end;
begin
    htp.p('<div class="mt-overview-wrap">');
    htp.p('<table class="mt-overview-table">');
    htp.p('<thead><tr>' ||
          '<th>Umgebung</th>' ||
          '<th>Datenbank</th>' ||
          '<th>Quelle (Host_DB_PDB)</th>' ||
          '<th>Ziel (Host_DB_PDB)</th>' ||
          '<th>Service_Name (Ziel)</th>' ||
          '<th>APEX Version</th>' ||
          '<th>Status</th>' ||
          '<th>URL</th>' ||
          '</tr></thead><tbody>');

    for r in (
        select umgebung,
               datenbank,
               quelle_host_db_pdb,
               ziel_host_db_pdb,
               service_name_ziel,
               apex_version,
               status,
               url
        from   mt_apex_migration_overview
        order  by row_sort
    ) loop
        l_rows := l_rows + 1;
        htp.p('<tr>' ||
              '<td>' || esc(r.umgebung) || '</td>' ||
              '<td>' || esc(r.datenbank) || '</td>' ||
              '<td>' || esc(r.quelle_host_db_pdb) || '</td>' ||
              '<td>' || esc(r.ziel_host_db_pdb) || '</td>' ||
              '<td>' || esc(r.service_name_ziel) || '</td>' ||
              '<td>' || esc(r.apex_version) || '</td>' ||
              '<td><span class="mt-badge mt-badge-ok">' || esc(r.status) || '</span></td>' ||
              '<td>' ||
              case
                  when r.url is null then null
                  else '<a class="mt-link" href="' || apex_escape.html_attribute(r.url) ||
                       '" target="_blank" rel="noopener noreferrer">' || esc(r.url) || '</a>'
              end ||
              '</td>' ||
              '</tr>');
    end loop;

    if l_rows = 0 then
        htp.p('<tr><td colspan="8">Keine Eintraege gefunden.</td></tr>');
    end if;

    htp.p('</tbody></table></div>');
exception
    when others then
        htp.p('<div class="t-Alert t-Alert--warning"><strong>APEX Migration Uebersicht:</strong> ' ||
              esc(sqlerrm) || '</div>');
end;~',
        p_attributes              => wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
            'expand_shortcuts', 'N')).to_clob);

    wwv_flow_imp_page.create_report_region(
        p_id                         => wwv_flow_imp.id(91500000000000110),
        p_name                       => 'APEX Migration ' || unistr('\00DC') || 'bersicht Report',
        p_title                      => 'APEX Migration ' || unistr('\00DC') || 'bersicht',
        p_template                   => wwv_flow_imp.id(10818657374759767),
        p_display_sequence           => 998,
        p_region_template_options    => '#DEFAULT#:t-Region--scrollBody',
        p_component_template_options => '#DEFAULT#:t-Report--altRowsDefault:t-Report--rowHighlight',
        p_display_point              => 'BODY',
        p_display_condition_type     => 'NEVER',
        p_source_type                => 'NATIVE_SQL_REPORT',
        p_query_type                 => 'SQL',
        p_source                     => wwv_flow_string.join(wwv_flow_t_varchar2(
            'select umgebung             as "Umgebung",',
            '       datenbank            as "Datenbank",',
            '       quelle_host_db_pdb   as "Quelle (Host_DB_PDB)",',
            '       ziel_host_db_pdb     as "Ziel (Host_DB_PDB)",',
            '       service_name_ziel    as "Service_Name (Ziel)",',
            '       apex_version         as "APEX Version",',
            '       status               as "Status",',
            '       case',
            '         when url is not null then ''<a href="'' || apex_escape.html_attribute(url) || ''" target="_blank">'' || apex_escape.html(url) || ''</a>''',
            '       end                  as "URL"',
            'from   mt_apex_migration_overview',
            'order  by row_sort')));

    wwv_flow_imp_page.create_region_column(
        p_id                      => wwv_flow_imp.id(91500000000000011),
        p_name                    => 'APEX$ROW_ACTION',
        p_session_state_data_type => 'VARCHAR2',
        p_item_type               => 'NATIVE_ROW_ACTION',
        p_display_sequence        => 10);

    wwv_flow_imp_page.create_region_column(
        p_id                      => wwv_flow_imp.id(91500000000000012),
        p_name                    => 'APEX$ROW_SELECTOR',
        p_session_state_data_type => 'VARCHAR2',
        p_item_type               => 'NATIVE_ROW_SELECTOR',
        p_display_sequence        => 20,
        p_attribute_01            => 'Y',
        p_attribute_02            => 'Y',
        p_attribute_03            => 'N');

    wwv_flow_imp_page.create_region_column(
        p_id                      => wwv_flow_imp.id(91500000000000013),
        p_name                    => 'OVERVIEW_ID',
        p_source_type             => 'DB_COLUMN',
        p_source_expression       => 'OVERVIEW_ID',
        p_data_type               => 'NUMBER',
        p_session_state_data_type => 'VARCHAR2',
        p_is_query_only           => false,
        p_item_type               => 'NATIVE_HIDDEN',
        p_display_sequence        => 30,
        p_attribute_01            => 'Y',
        p_is_primary_key          => true,
        p_include_in_export       => false);

    wwv_flow_imp_page.create_region_column(
        p_id                      => wwv_flow_imp.id(91500000000000014),
        p_name                    => 'ROW_SORT',
        p_source_type             => 'DB_COLUMN',
        p_source_expression       => 'ROW_SORT',
        p_data_type               => 'NUMBER',
        p_session_state_data_type => 'VARCHAR2',
        p_is_query_only           => false,
        p_item_type               => 'NATIVE_NUMBER_FIELD',
        p_heading                 => 'Sort',
        p_display_sequence        => 40,
        p_value_alignment         => 'RIGHT',
        p_is_required             => false,
        p_enable_filter           => true,
        p_filter_lov_type         => 'NONE',
        p_enable_sort_group       => true,
        p_enable_hide             => true,
        p_include_in_export       => true);

    wwv_flow_imp_page.create_region_column(
        p_id                      => wwv_flow_imp.id(91500000000000015),
        p_name                    => 'UMGEBUNG',
        p_source_type             => 'DB_COLUMN',
        p_source_expression       => 'UMGEBUNG',
        p_data_type               => 'VARCHAR2',
        p_session_state_data_type => 'VARCHAR2',
        p_is_query_only           => false,
        p_item_type               => 'NATIVE_TEXT_FIELD',
        p_heading                 => 'Umgebung',
        p_display_sequence        => 50,
        p_value_alignment         => 'LEFT',
        p_attribute_05            => 'BOTH',
        p_max_length              => 100,
        p_enable_filter           => true,
        p_filter_operators        => 'C:S:CASE_INSENSITIVE:REGEXP',
        p_filter_lov_type         => 'DISTINCT',
        p_enable_sort_group       => true,
        p_enable_hide             => true,
        p_include_in_export       => true);

    wwv_flow_imp_page.create_region_column(
        p_id                      => wwv_flow_imp.id(91500000000000016),
        p_name                    => 'DATENBANK',
        p_source_type             => 'DB_COLUMN',
        p_source_expression       => 'DATENBANK',
        p_data_type               => 'VARCHAR2',
        p_session_state_data_type => 'VARCHAR2',
        p_is_query_only           => false,
        p_item_type               => 'NATIVE_TEXT_FIELD',
        p_heading                 => 'Datenbank',
        p_display_sequence        => 60,
        p_value_alignment         => 'LEFT',
        p_attribute_05            => 'BOTH',
        p_max_length              => 200,
        p_enable_filter           => true,
        p_filter_operators        => 'C:S:CASE_INSENSITIVE:REGEXP',
        p_filter_lov_type         => 'DISTINCT',
        p_enable_sort_group       => true,
        p_enable_hide             => true,
        p_include_in_export       => true);

    wwv_flow_imp_page.create_region_column(
        p_id                      => wwv_flow_imp.id(91500000000000017),
        p_name                    => 'QUELLE_HOST_DB_PDB',
        p_source_type             => 'DB_COLUMN',
        p_source_expression       => 'QUELLE_HOST_DB_PDB',
        p_data_type               => 'VARCHAR2',
        p_session_state_data_type => 'VARCHAR2',
        p_is_query_only           => false,
        p_item_type               => 'NATIVE_TEXT_FIELD',
        p_heading                 => 'Quelle (Host_DB_PDB)',
        p_display_sequence        => 70,
        p_value_alignment         => 'LEFT',
        p_attribute_05            => 'BOTH',
        p_max_length              => 1000,
        p_enable_filter           => true,
        p_filter_operators        => 'C:S:CASE_INSENSITIVE:REGEXP',
        p_filter_lov_type         => 'NONE',
        p_enable_sort_group       => true,
        p_enable_hide             => true,
        p_include_in_export       => true);

    wwv_flow_imp_page.create_region_column(
        p_id                      => wwv_flow_imp.id(91500000000000018),
        p_name                    => 'ZIEL_HOST_DB_PDB',
        p_source_type             => 'DB_COLUMN',
        p_source_expression       => 'ZIEL_HOST_DB_PDB',
        p_data_type               => 'VARCHAR2',
        p_session_state_data_type => 'VARCHAR2',
        p_is_query_only           => false,
        p_item_type               => 'NATIVE_TEXT_FIELD',
        p_heading                 => 'Ziel (Host_DB_PDB)',
        p_display_sequence        => 80,
        p_value_alignment         => 'LEFT',
        p_attribute_05            => 'BOTH',
        p_max_length              => 1000,
        p_enable_filter           => true,
        p_filter_operators        => 'C:S:CASE_INSENSITIVE:REGEXP',
        p_filter_lov_type         => 'NONE',
        p_enable_sort_group       => true,
        p_enable_hide             => true,
        p_include_in_export       => true);

    wwv_flow_imp_page.create_region_column(
        p_id                      => wwv_flow_imp.id(91500000000000019),
        p_name                    => 'SERVICE_NAME_ZIEL',
        p_source_type             => 'DB_COLUMN',
        p_source_expression       => 'SERVICE_NAME_ZIEL',
        p_data_type               => 'VARCHAR2',
        p_session_state_data_type => 'VARCHAR2',
        p_is_query_only           => false,
        p_item_type               => 'NATIVE_TEXT_FIELD',
        p_heading                 => 'Service_Name (Ziel)',
        p_display_sequence        => 90,
        p_value_alignment         => 'LEFT',
        p_attribute_05            => 'BOTH',
        p_max_length              => 200,
        p_enable_filter           => true,
        p_filter_operators        => 'C:S:CASE_INSENSITIVE:REGEXP',
        p_filter_lov_type         => 'DISTINCT',
        p_enable_sort_group       => true,
        p_enable_hide             => true,
        p_include_in_export       => true);

    wwv_flow_imp_page.create_region_column(
        p_id                      => wwv_flow_imp.id(91500000000000020),
        p_name                    => 'APEX_VERSION',
        p_source_type             => 'DB_COLUMN',
        p_source_expression       => 'APEX_VERSION',
        p_data_type               => 'VARCHAR2',
        p_session_state_data_type => 'VARCHAR2',
        p_is_query_only           => false,
        p_item_type               => 'NATIVE_TEXT_FIELD',
        p_heading                 => 'APEX Version',
        p_display_sequence        => 100,
        p_value_alignment         => 'LEFT',
        p_attribute_05            => 'BOTH',
        p_max_length              => 200,
        p_enable_filter           => true,
        p_filter_operators        => 'C:S:CASE_INSENSITIVE:REGEXP',
        p_filter_lov_type         => 'DISTINCT',
        p_enable_sort_group       => true,
        p_enable_hide             => true,
        p_include_in_export       => true);

    wwv_flow_imp_page.create_region_column(
        p_id                      => wwv_flow_imp.id(91500000000000021),
        p_name                    => 'STATUS',
        p_source_type             => 'DB_COLUMN',
        p_source_expression       => 'STATUS',
        p_data_type               => 'VARCHAR2',
        p_session_state_data_type => 'VARCHAR2',
        p_is_query_only           => false,
        p_item_type               => 'NATIVE_TEXT_FIELD',
        p_heading                 => 'Status',
        p_display_sequence        => 110,
        p_value_alignment         => 'LEFT',
        p_attribute_05            => 'BOTH',
        p_max_length              => 100,
        p_enable_filter           => true,
        p_filter_operators        => 'C:S:CASE_INSENSITIVE:REGEXP',
        p_filter_lov_type         => 'DISTINCT',
        p_enable_sort_group       => true,
        p_enable_hide             => true,
        p_include_in_export       => true);

    wwv_flow_imp_page.create_region_column(
        p_id                      => wwv_flow_imp.id(91500000000000022),
        p_name                    => 'URL',
        p_source_type             => 'DB_COLUMN',
        p_source_expression       => 'URL',
        p_data_type               => 'VARCHAR2',
        p_session_state_data_type => 'VARCHAR2',
        p_is_query_only           => false,
        p_item_type               => 'NATIVE_TEXT_FIELD',
        p_heading                 => 'URL',
        p_display_sequence        => 120,
        p_value_alignment         => 'LEFT',
        p_attribute_05            => 'BOTH',
        p_max_length              => 1000,
        p_enable_filter           => true,
        p_filter_operators        => 'C:S:CASE_INSENSITIVE:REGEXP',
        p_filter_lov_type         => 'NONE',
        p_enable_sort_group       => true,
        p_enable_hide             => true,
        p_include_in_export       => true);

    wwv_flow_imp_page.create_interactive_grid(
        p_id                         => wwv_flow_imp.id(91500000000000030),
        p_internal_uid               => 91500000000000030,
        p_is_editable                => true,
        p_edit_operations            => 'i:u:d',
        p_lost_update_check_type     => 'VALUES',
        p_add_row_if_empty           => false,
        p_submit_checked_rows        => false,
        p_lazy_loading               => false,
        p_requires_filter            => false,
        p_show_nulls_as              => '',
        p_select_first_row           => false,
        p_fixed_row_height           => true,
        p_pagination_type            => 'SCROLL',
        p_show_total_row_count       => true,
        p_no_data_found_message      => 'Keine Eintraege gefunden.',
        p_show_toolbar               => true,
        p_toolbar_buttons            => 'SEARCH_FIELD:ACTIONS_MENU:RESET:SAVE',
        p_enable_save_public_report  => false,
        p_enable_subscriptions       => false,
        p_enable_flashback           => false,
        p_define_chart_view          => false,
        p_enable_download            => true,
        p_download_formats           => 'CSV:XLSX',
        p_enable_mail_download       => false,
        p_fixed_header               => 'PAGE',
        p_show_icon_view             => false,
        p_show_detail_view           => false);

    wwv_flow_imp_page.create_ig_report(
        p_id                  => wwv_flow_imp.id(91500000000000031),
        p_interactive_grid_id => wwv_flow_imp.id(91500000000000030),
        p_static_id           => '915001',
        p_type                => 'PRIMARY',
        p_default_view        => 'GRID',
        p_rows_per_page       => 50,
        p_show_row_number     => false,
        p_settings_area_expanded => true);

    wwv_flow_imp_page.create_ig_report_view(
        p_id                     => wwv_flow_imp.id(91500000000000032),
        p_report_id              => wwv_flow_imp.id(91500000000000031),
        p_view_type              => 'GRID',
        p_stretch_columns        => true,
        p_srv_exclude_null_values => false,
        p_srv_only_display_columns => true,
        p_edit_mode              => false);

    wwv_flow_imp_page.create_ig_report_column(p_id=>wwv_flow_imp.id(91500000000000041), p_view_id=>wwv_flow_imp.id(91500000000000032), p_display_seq=>1, p_column_id=>wwv_flow_imp.id(91500000000000011), p_is_visible=>true, p_is_frozen=>true);
    wwv_flow_imp_page.create_ig_report_column(p_id=>wwv_flow_imp.id(91500000000000042), p_view_id=>wwv_flow_imp.id(91500000000000032), p_display_seq=>2, p_column_id=>wwv_flow_imp.id(91500000000000012), p_is_visible=>true, p_is_frozen=>true);
    wwv_flow_imp_page.create_ig_report_column(p_id=>wwv_flow_imp.id(91500000000000043), p_view_id=>wwv_flow_imp.id(91500000000000032), p_display_seq=>3, p_column_id=>wwv_flow_imp.id(91500000000000014), p_is_visible=>false, p_is_frozen=>false, p_sort_order=>1, p_sort_direction=>'ASC', p_sort_nulls=>'LAST');
    wwv_flow_imp_page.create_ig_report_column(p_id=>wwv_flow_imp.id(91500000000000044), p_view_id=>wwv_flow_imp.id(91500000000000032), p_display_seq=>4, p_column_id=>wwv_flow_imp.id(91500000000000015), p_is_visible=>true, p_is_frozen=>false);
    wwv_flow_imp_page.create_ig_report_column(p_id=>wwv_flow_imp.id(91500000000000045), p_view_id=>wwv_flow_imp.id(91500000000000032), p_display_seq=>5, p_column_id=>wwv_flow_imp.id(91500000000000016), p_is_visible=>true, p_is_frozen=>false);
    wwv_flow_imp_page.create_ig_report_column(p_id=>wwv_flow_imp.id(91500000000000046), p_view_id=>wwv_flow_imp.id(91500000000000032), p_display_seq=>6, p_column_id=>wwv_flow_imp.id(91500000000000017), p_is_visible=>true, p_is_frozen=>false, p_width=>360);
    wwv_flow_imp_page.create_ig_report_column(p_id=>wwv_flow_imp.id(91500000000000047), p_view_id=>wwv_flow_imp.id(91500000000000032), p_display_seq=>7, p_column_id=>wwv_flow_imp.id(91500000000000018), p_is_visible=>true, p_is_frozen=>false, p_width=>280);
    wwv_flow_imp_page.create_ig_report_column(p_id=>wwv_flow_imp.id(91500000000000048), p_view_id=>wwv_flow_imp.id(91500000000000032), p_display_seq=>8, p_column_id=>wwv_flow_imp.id(91500000000000019), p_is_visible=>true, p_is_frozen=>false);
    wwv_flow_imp_page.create_ig_report_column(p_id=>wwv_flow_imp.id(91500000000000049), p_view_id=>wwv_flow_imp.id(91500000000000032), p_display_seq=>9, p_column_id=>wwv_flow_imp.id(91500000000000020), p_is_visible=>true, p_is_frozen=>false);
    wwv_flow_imp_page.create_ig_report_column(p_id=>wwv_flow_imp.id(91500000000000051), p_view_id=>wwv_flow_imp.id(91500000000000032), p_display_seq=>10, p_column_id=>wwv_flow_imp.id(91500000000000021), p_is_visible=>true, p_is_frozen=>false);
    wwv_flow_imp_page.create_ig_report_column(p_id=>wwv_flow_imp.id(91500000000000052), p_view_id=>wwv_flow_imp.id(91500000000000032), p_display_seq=>11, p_column_id=>wwv_flow_imp.id(91500000000000022), p_is_visible=>true, p_is_frozen=>false, p_width=>420);

    wwv_flow_imp_page.create_page_process(
        p_id                     => wwv_flow_imp.id(91500000000000060),
        p_process_sequence       => 10,
        p_process_point          => 'AFTER_SUBMIT',
        p_region_id              => wwv_flow_imp.id(91500000000000010),
        p_process_type           => 'NATIVE_IG_DML',
        p_process_name           => 'APEX Migration ' || unistr('\00DC') || 'bersicht - Save Interactive Grid Data',
        p_attribute_01           => 'REGION_SOURCE',
        p_attribute_05           => 'Y',
        p_attribute_06           => 'Y',
        p_attribute_08           => 'Y',
        p_error_display_location => 'INLINE_IN_NOTIFICATION',
        p_internal_uid           => 91500000000000060);

    -- Remove old visible pages. Page 9 is intentionally kept as detail page.
    for p in 2 .. 8 loop
        begin
            wwv_flow_imp_page.remove_page(p_flow_id => l_app_id, p_page_id => p);
        exception
            when others then
                null;
        end;
    end loop;

    -- Hide stale imported navigation entries for removed pages.
    -- wwv_flow_imp_shared has no delete API for list items, but importing the
    -- same item id with ITEM_DISPLAYED = N updates the item cleanly.
    for r in (
        select list_entry_id, entry_text, entry_target, display_sequence
        from   apex_application_list_entries
        where  application_id = l_app_id
        and    list_name = 'Navigation Menu'
        and    (
                  entry_text in ('Home',
                                 'Fachverfahren',
                                 'Caesar Orders',
                                 'Checkliste',
                                 'Service Name Audit',
                                 'Server Inventory')
               or regexp_like(entry_target, '[:.]([2-8])[:.]')
               )
    ) loop
        begin
            wwv_flow_imp_shared.create_list_item(
                p_id                         => r.list_entry_id,
                p_list_id                    => l_nav_list_id,
                p_list_item_type             => 'LINK',
                p_list_item_status           => 'PUBLIC',
                p_item_displayed             => 'N',
                p_list_item_display_sequence => nvl(r.display_sequence, 900),
                p_list_item_link_text        => r.entry_text,
                p_list_item_link_target      => r.entry_target,
                p_list_item_current_type     => 'TARGET_PAGE');
        exception
            when others then
                null;
        end;
    end loop;

    -- Rename/repoint existing Page 1 navigation entry if it exists.
    for r in (
        select list_entry_id
        from   apex_application_list_entries
        where  application_id = l_app_id
        and    list_name = 'Navigation Menu'
        and    entry_target like '%:1:%'
    ) loop
        wwv_flow_imp_shared.set_list_item_sequence(
            p_id            => r.list_entry_id,
            p_item_sequence => 10);
        wwv_flow_imp_shared.set_list_item_link_text(
            p_id        => r.list_entry_id,
            p_link_text => 'APEX Migration ' || unistr('\00DC') || 'bersicht');
        wwv_flow_imp_shared.set_list_item_link_target(
            p_id          => r.list_entry_id,
            p_link_target => 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::');
    end loop;

    -- Ensure Live Vergleich has a visible navigation entry.
    begin
        wwv_flow_imp_shared.create_list_item(
            p_id                          => wwv_flow_imp.id(91500000000000050),
            p_list_id                     => l_nav_list_id,
            p_list_item_type              => 'LINK',
            p_list_item_status            => 'PUBLIC',
            p_item_displayed              => 'Y',
            p_list_item_display_sequence  => 20,
            p_list_item_link_text         => 'Live Vergleich',
            p_list_item_link_target       => 'f?p=&APP_ID.:10:&APP_SESSION.::&DEBUG.:::',
            p_list_item_icon              => 'fa-search',
            p_list_item_current_type      => 'TARGET_PAGE',
            p_list_item_current_for_pages => '10');
    exception
        when others then
            null;
    end;

    wwv_flow_imp.import_end(p_auto_install_sup_obj => false);
    commit;
end;
/

-- Verification: visible/final pages plus hidden technical/login pages.
select page_id, page_name
from   apex_application_pages
where  application_id = (
           select min(application_id)
           from   apex_applications
           where  workspace = 'MIGRATION'
           and    application_name = 'Migration_Tracker'
       )
order  by page_id;

-- Verification: stale navigation entries may remain in metadata, but are hidden
-- by page CSS on the final visible pages.
select entry_text, entry_target
from   apex_application_list_entries
where  application_id = (
           select min(application_id)
           from   apex_applications
           where  workspace = 'MIGRATION'
           and    application_name = 'Migration_Tracker'
       )
and    list_name = 'Navigation Menu'
order  by display_sequence;
